# build environment
FROM node:11.10-slim as build

RUN apt-get update && \
  apt-get -y install git && \
  rm -rf /var/lib/apt/lists/* && \
  mkdir /workspace && \
  cd /workspace && \
  git clone https://github.com/Suezenv/make-sense.git && \
  cd make-sense

WORKDIR /workspace/make-sense

RUN npm install

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /workspace/make-sense/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
